name: bar_restaurant_app
description: A flutter app to discover bars and restaurants.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bmnav: ^0.3.4
  flutter_map:
  geolocator: ^5.3.0
  flutter_launcher_name: ^0.0.1
  flutter_local_notifications: ^1.4.0
  path_provider: ^1.6.5 
  location_permissions: ^2.0.5
  
  # iOS Icons and Fonts
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "STL Bars & Restaurants"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  # Icons and Graphics
    - assets/images/map.png
    - assets/images/explore.png
    - assets/images/about.png
    - assets/images/noimage.png
  # General Photographs

  # Bar Location Images
    - assets/images/bar-images/Fireplace-Bar.jpg
    - assets/images/bar-images/Little-Jamaica.jpg
    - assets/images/bar-images/Big-As.jpg
    - assets/images/bar-images/Drinking-Horn.jpg
  # Restaurant Location Images
    - assets/images/restaurant-images/La-Bonne-Bouchee.jpg
    - assets/images/restaurant-images/Perfect-Taste.jpg
    - assets/images/restaurant-images/Wei-Hong.jpg
    - assets/images/restaurant-images/HuHot.jpg
    - assets/images/restaurant-images/Troy.jpg
    - assets/images/restaurant-images/Nippon-Tei.jpg
    - assets/images/restaurant-images/Himalayan-Yeti.jpg
    - assets/images/restaurant-images/Everest.png
  # Cropped Images
    - assets/images/cropped/Fireplace-Bar-Cropped.jpg 
    - assets/images/cropped/La-Bonne-Bouchee-Cropped.jpg
    - assets/images/cropped/Wei-Hong-Cropped.jpg
    - assets/images/cropped/HuHot-Cropped.jpg
    - assets/images/cropped/Troy-Cropped.jpg
    - assets/images/cropped/Nippon-Tei-Cropped.jpg
    - assets/images/cropped/Himalayan-Yeti-Cropped.jpg
    - assets/images/cropped/Everest-Cropped.png
    - assets/images/cropped/Little-Jamaica-Cropped.jpg
    - assets/images/cropped/Big-As-Cropped.jpg
    - assets/images/cropped/Drinking-Horn-Cropped.jpg